title: ProductPicks
description: >-
  Honest, no-fluff buying guides and product comparisons.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
permalink: /:categories/:title/

show_excerpts: true
